# GET https://newsapi.org/v2/top-headlines?country=in&category=business&apiKey=418e0bf5fb6048339c8b87f1629b6bfb HTTP/1.1
# no
# hmm setai bujhlam na case, duto jaegae alda alda jinish likhse
# chaar baad de shuye por ar ki
# shon
# oh na, https: ee dise
# arekta jinish
# bujla?
# hmm
# eta akbar dekh bypass kora jaekina
# cuz
# nale amader website theke cholbe If-None-Match: mane
# CORS enabled sudhu matro localhost er jnnoe kora hoeche
# er mane
# amader browser e testing er jnnoee sudhu chlbe jinish TAki korum taleh onno kono api amar jana nei
# hmm arekta ache, otar per day request er count tao beshi
# so dekha jete paare, else oi bypass korte hobe , jodi kora jaye
# otar link ta dibi
# jegulo ache, mostly shob orom ee jete exception seta ki tor jana???
# narre
# ami oitar kothai bolchilam ooi something new dataio na ki akta
# but otao same
# jaehok dekh bihan er ota diye bypass kora jachhe kina
# na hochhe If-None-Match: 
# bihan er oi link ta dekha
# dara
# jodi erokom ee hoe thaake
# then paid api chara ar kono option nei
# cuz e toh amae just temporary er jnno access debe amader ip ta theke
# so machine er ip reset holei gone
# shonna bu tui ektu bolish ei byaparta aditya sir ke amio bolbo
# hmm
# acha dara 1 sec

GET https://gnews.io/api/v4/search?q=finance&country=in&token=2c7844cedbb5f28289214b307b51ab80
# GET http://newsapi.org/v2/top-headlines?country=in&category=business&apiKey=418e0bf5fb6048339c8b87f1629b6bfb HTTP/1.1